[global]
keep_generations = 3
; 备份的目录
root_directory = /media/pool0/vm/192.168.15.248/ars
vmdkmgr_path = /data/vmmgr/bin/bin/vmdkmgr
;
runcfgroot = /data/vmmgr/vm/192.168.15.148/run
profile_all_vm_file_name = vmcdp_all_vm.profile
mdfsroot = /media/pool0/
snapshotcfg = /data/vmmgr/cfg/192.168.15.248snapshot.conf

[fusioncloud]
projectDomainName = Default
userDomainName = Default
projectId = 0869f5b3b3d3419fb49275e57002eb92
server = 192.168.15.248
serverIp = 192.168.15.248
url = https://192.168.15.248
port = 5000
userName = admin
passWord = dbArPQmVCnQ0lgLhngE9Rw==
manage_port = 443
isOpenstack = true
